koinos/koinos-proto

- .travis.yml
> Bump protobuf

- ci/after_success.sh
> Publish tags

- koinos/block_store/block_store.proto
- koinos/chain/chain.proto
- koinos/chain/system_calls.proto
- koinos/common.proto
- koinos/contracts/token/token.proto
- koinos/options.proto
- koinos/protocol/protocol.proto
- koinos/rpc/block_store/block_store_rpc.proto
- koinos/rpc/chain/chain_rpc.proto
- koinos/rpc/contract_meta_store/contract_meta_store_rpc.proto
- koinos/rpc/mempool/mempool_rpc.proto
- koinos/rpc/transaction_store/transaction_store_rpc.proto
- koinos/transaction_store/transaction_store.proto
> Remove blobs and rename `koinos_bytes_type` to `btype`

- koinos/broadcast/broadcast.proto
Resolves koinos/koinos-chain#541.
> Add pending transaction failed broadcast message

- koinos/chain/system_calls.proto
Related to koinos/koinos-chain#532.
> Update `put_object` result

- koinos/chain/authority.proto
- koinos/chain/chain.proto
- koinos/protocol/protocol.proto
Closes koinos/koinos-chain#570
> Add proto types for authority system

- koinos/chain/system_calls.proto
- koinos/protocol/protocol.proto
- koinos/protocol/system_call_ids.proto
- koinos/protocol/value.proto
Resolves koinos/koinos-chain#576.
> Finalize system calls

- koinos/chain/chain.proto
Related to koinos/koinos-chain#583.
> Add bandwidth data to genesis data

- koinos/protocol/protocol.proto
Resolves koinos/koinos-system-contracts#50
> Add approved proposals to block header

- koinos/chain/chain.proto
- koinos/chain/system_call_ids.proto
- koinos/chain/system_calls.proto
Resolves koinos/koinos-crypto-cpp#25
Adds messages for `verify_vrf_proof` system call.
> Verify vrf proof

- .travis.yml
- ci/install.sh
Resolves #114
Use @roaminroe's modified `as-proto-gen` package
> Use roaminroe/as-proto-gen #114

- koinos/contracts/governance/governance.proto
- koinos/contracts/token/token.proto
Related to koinos/koinos-system-contracts#41.
> Governance (Proto)

- ci/after_success.sh
Regenerates proto-as `index.ts` file.
> Regenerate proto-as index.ts

- .travis.yml
- ci/after_success.sh
Generate proto-as using correct generator for publishing as an npm package
> Bump AS Generator

- ci/after_success.sh
- ci/install.sh
Bumps the npm package version of `koinos-proto-as`
> Bump as version

- ci/after_success.sh
Only bump npm version when files have changed
> Only bump version when files have changed

- koinos/chain/system_call_ids.proto
- koinos/chain/system_calls.proto
Resolves koinos/koinos-chain#655
Adds proto messages for `get_chain_id` system call
> Add get_chain_id system call

- koinos/chain/chain.proto
- koinos/chain/return_codes.proto
- koinos/chain/system_call_ids.proto
- koinos/chain/system_calls.proto
Resolves koinos/koinos-chain#649.
Changes system calls that previously asserted on failure to returning success/failure error codes.
> Update system call definitions to allow for error handling in contracts

- koinos/chain/chain.proto
- koinos/chain/system_calls.proto
Makes `apply_*` thunks void again and adds `error_info` message.
> Updates for newer and better error handling

- koinos/chain/error.proto
- koinos/chain/system_call_ids.proto
- koinos/chain/system_calls.proto
Adds proto messages for `get_operation` system call
> Add proto messages for get_operation

- koinos/chain/system_calls.proto
Make `call_result` bytes again
> Make `call_result` bytes again

- koinos/chain/authority.proto
- koinos/chain/system_calls.proto
Add custom data to authorize message
> Add custom args to authority messages

- koinos/contracts/pob/pob.proto
> Add pob proto file

- koinos/contracts/pob/pob.proto
Adds consensus parameters to proof of burn contract
> Add consensus_parameters to proof of burn

- koinos/rpc/chain/chain_rpc.proto
Related to koinos/koinos-chain#727
> Allow transactions to be submitted without broadcasting

- koinos/contracts/claim/claim.proto
Involves  koinos/koinos-chain#248
Add koin address
> Add koin_address to claim argument

- koinos/contracts/pob/pob.proto
Involves koinos/koinos-system-contracts-as#30
Add new PoB endpoint
> Add get_public_key endpoint messages

- koinos/chain/value.proto
Removes floats from `value_type`.
> Remove floats from value_type

- koinos/chain/system_calls.proto
Add compressed flag to `recover_public_key` and `verify_signature`.
> Add compressed flag

- koinos/contracts/claim/claim.proto
> Add check claim

- koinos/chain/system_calls.proto
Removes `system_authorization_type`
> Remove system_authorization_type

- koinos/contracts/pob/pob.proto
- koinos/contracts/token/token.proto
Resolves koinos/koinos-system-contracts-as#36
Adds messages to track delays for setting public keys and transferring VHP
> Add messages to implement public key and VHP delays

- koinos/contracts/koin/koin.proto
- koinos/contracts/token/token.proto
- koinos/contracts/vhp/vhp.proto
Move KOIN and VHP specific messages to separate proto files and change map to repeated field
> Refactor PoB Delay

- koinos/contracts/pob/pob.proto
Involves koinos/koinos-system-contracts-as#35
Add `minimum_block_time` to the proof-of-burn consensus parameters.
> Add minimum block time parameter

- koinos/contracts/pob/pob.proto
Involves https://github.com/koinos/koinos-system-contracts-as/issues/35
Add `update_consensus_parameters` messages.
> Add update_consensus_parameters messages

- koinos/contracts/resources/resources.proto
- koinos/protocol/protocol.proto
Changes needed to update the resource contract as well as differentiating between used and charged resources in block receipt.
> Resource updates

- koinos/contracts/name_service/name_service.proto
Added arguments/results for a system name service contract.
> Add protobuf declarations for system name service contract

- koinos/chain/system_call_ids.proto
Resolves koinoss/koinos-contracts-as/#66
Adds `get_contract_name` and `get_contract_address` SID
> Add SIDs for nameservice system calls

- koinos/account_history/account_history.proto
- koinos/rpc/account_history/account_history_rpc.proto
Resolves koinos/koinos-account-history#2
Adds proto files for Account History
> Account history

- koinos/chain/value.proto
Resolves #174
Use correct go package for value.proto
> Use correct go package for value.proto

- .travis.yml
- ci/after_success.sh
- ci/install.sh
Resolves #179
Bumps `as-proto-gen` to fix AS default de/serialization.
> 179 as proto gen

- .github/workflows/branch-cleanup.yml
- ci/after_success.sh
Resolves #172
Fixes problems in `after_success.sh` revealed by adding `set -e`
> 172 fix after success

- ci/after_success.sh
Standardize variable styling and use the tag version string with npm
> More after success changes

- .travis.yml
Resolves #183 
Generate AS to properly handle oneof deserialization
> As Proto oneof deserialization

- .travis.yml
Reverts koinos/koinos-proto#184
> Revert "As Proto oneof deserialization"

- ci/after_success.sh
Resolves #186
Fix bugs with as/js versioning
https://github.com/koinos/koinos-proto-as/releases/tag/v1.0.2-rc1
https://github.com/koinos/koinos-proto-as/commit/1b00d84b820c3478fba29e3e3f32678d1b8a67b3
https://github.com/koinos/koinos-proto-js/releases/tag/v1.0.2-rc1
https://github.com/koinos/koinos-proto-js/commit/58e3770bec95a645cb37c222c83499441b97a021
> Fix bugs with as/js versioning

- ci/after_success.sh
Resolves #188
Commit npm version updates to master on tag
> Commit npm version updates to master on tag

- koinos/rpc/mempool/mempool_rpc.proto
Related to #192.
Add `block_id` to `check_pending_account_resource_request`.
> Add an additional parameter called `block_id` to `check_pending_account_resource_request`

- koinos/contracts/koin/koin.proto
- koinos/mempool/mempool.proto
- koinos/rpc/account_history/account_history_rpc.proto
- koinos/rpc/services.proto
Resolves #200
Add other Koinos services and fix protoc warnings
> Add other Koinos services and fix protoc warnings

- koinos/rpc/chain/chain_rpc.proto
- koinos/rpc/services.proto
Involves koinos/koinos-chain#799
Add `invoke_system_call` rpc messages
> Chain system call

- koinos/chain/system_call_ids.proto
- koinos/chain/system_calls.proto
Add a new system call id required in koinos/koinos-chain#806
N/A
> feat: add new get_contract_metadata system call

- ci/build.sh
- ci/install.sh
> Version go cmd

- .travis.yml
> Fix gen cpp

- .travis.yml
> #219: Only checkout a branch if TRAVIS_TAG is not set (not a tag build)

- .travis.yml
> #224: Get short commit hash

- .github/workflows/branch-cleanup.yml
> Clone branch again

- koinos/rpc/mempool/mempool_rpc.proto
Reverts koinos/koinos-proto#223
> Revert "Add new request/response to check transaction validity in mempool"

- .github/workflows/branch-cleanup.yml
> ls-remote on correct repo

- .github/workflows/branch-cleanup.yml
> Try specifying repo_url with access token explicitly

- .github/workflows/branch-cleanup.yml
> Don't pass an argument to popd

- koinos/rpc/chain/chain_rpc.proto
Resolves #237
Adds propose block chain RPC
> #237: Add propose block chain RPC

- .travis.yml
> Remove comment from proto-cpp version bump

- .travis.yml
> Properly stage js version bump on tag

- koinos/standards/kcs3.proto
Resolves #250.
Adds the KCS-3 standard.
> Adds KCS-3

- koinos/standards/kcs4.proto
Remove KCS-4 direction enum as requested in koinos/koinos-contract-standards#14
> Remove KCS-4 direction enum

- koinos/standards/kcs1.proto
- koinos/standards/kcs3.proto
- koinos/standards/kcs4.proto
Removes storage objects, which are implementation details, from the KCS proto files.
> Remove internal storage objects from KCS standard proto files
