- koinos/block_store/block_store.proto
- koinos/broadcast/broadcast.proto
- koinos/chain/chain.proto
- koinos/common.proto
- koinos/contracts/pow/pow.proto
- koinos/protocol/protocol.proto
- koinos/protocol/system_call_ids.proto
- koinos/rpc/block_store/block_store_rpc.proto
- koinos/rpc/chain/chain_rpc.proto
- koinos/rpc/mempool/mempool_rpc.proto
All uint64 values now have the JS_STRING tag attached.
Also remove db_ prefix from values.
Resolves #19
> Add JS_STRING tag 

- koinos/chain/chain.proto
- koinos/chain/system_calls.proto
Resolves koinos/koinos-chain#694
Refactor `result` to be a oneof object bytes or error_data.
> Embedd error_data in a one of

- .travis.yml
Resolves koinos/koinos-sdk-as#34
Uses a branch of `EmbeddedProto` that correctly generate signed integer enums
https://github.com/koinos/koinos-proto-embedded-cpp/blob/e2fcdaddb0ff7caf547db2d92f7978c1052966d0/libraries/proto_embedded/generated/koinos/chain/error.h#L41-L66
> Build EmbeddedProto with `negative-enums` branch

- koinos/broadcast/broadcast.proto
Add a flag to indicate whether an accepted block is the new head or not.
> `head` flag on `block_accepted`

- koinos/contracts/pob/pob.proto
Adds `quantum_length` to encode all parameters and reduce size of 32 bit to match expected value range.
> Add quantum_length to consensus_parameters and make fields uint32

- koinos/chain/error.proto
Adds an error to indicate a block is prior to irreversibility.
> Adds `pre_block_irreversibility` error code

- koinos/contracts/pob/pob.proto
Removes the unused minimum block parameter.
> Remove minimum block time from pob consensus parameters

- koinos/contracts/pob/pob.proto
Resolves #190.
Fixes the ordering of the `register_public_key_event`.
> Swap the order of fields in the `register_public_key event`

- ci/after_success.sh
Disable uploading generated openapi while openapi is not being generated
> Disable uploading generated openapi while openapi is not being generated

- koinos/chain/system_calls.proto
Rename the `get_contract_metadata_result` `contract_metadata` field into `value` to comply with other syscalls format.
> rename field in `get_contract_metadata_result` into `value`

- koinos/rpc/mempool/mempool_rpc.proto
Resolves #222.
Adds a new mempool RPC call that essentially combines the current checks into a single RPC which checks both resources and nonce validity.
Note that we make the optional `block_id` index number 1000 to allow for expansion of this call while keeping the optional arguments at the end.
> Add new request/response to check transaction validity in mempool

- .github/workflows/branch-cleanup.yml
Resolves 
Simplifies the branch cleanup (no clone). The failures appeared to be from a bad token. I have tested the commands locally with the a fine grained token expiring Jan 1, 2025.
> Simplify branch cleanup

- .travis.yml
Resolves #225
Updates the proto-cpp version on a tag build.
> #225: Bump proto-cpp version when proto is tagged

- .travis.yml
TRAVIS_BRANCH can be set to the branch name, or a tag. This causes an error when updating the npm version because travis attempts to push the version update to the tag branch, not master.
This can be seen in CI logs, but also in the `koinos-proto-as` repos where they have the correct tags, with the correct versions. But all tags are detached heads and were never pushed to `master`.
> Determine the correct branch as an env var 

- .travis.yml
- koinos/rpc/mempool/mempool_rpc.proto
Related to koinos/koinos-mempool#101.
Adds an RPC call to retrieve pending account rc from the mempool.
> Add mempool RPC to retrieve pending account rc

- koinos/rpc/mempool/mempool_rpc.proto
Adds mempool RPC `get_pending_nonce` to return a pending nonce from the mempool if the payee has a transaction in the mempool.
```
❯ ./run.sh pending_nonce                               
~/dev/koinos-integration-tests/tests/pending_nonce ~/dev/koinos-integration-tests
[+] Running 6/6
✔ Network pending_nonce_default          Created                                                                                                                                                                                                     0.1s 
✔ Container pending_nonce-amqp-1         Started                                                                                                                                                                                                     0.2s 
✔ Container …
```
> Add messages for get_pending_nonce mempool RPC

- .travis.yml
When making proto releases, CI tags the version, but also fails. See the following:
https://app.travis-ci.com/github/koinos/koinos-proto/builds/272880003?serverType=git
https://app.travis-ci.com/github/koinos/koinos-proto/builds/272880321?serverType=git
https://app.travis-ci.com/github/koinos/koinos-proto/builds/272880323?serverType=git
And the version was still bumped (as desired):
https://github.com/koinos/koinos-proto-js/commit/34a9175101111025c8f4e9b951100ea184c4a6a1
This will allow npm version to succeed if the version is identical, making CI pass.
> NPM allow same version

- koinos/chain/error.proto
- koinos/rpc/mempool/mempool_rpc.proto
Resolves #263
Adds `mempool.get_pending_transaction_count` and `pending_transaction_limit_exceeded` error.
> #263: Add get_pending_transaction_count and error

- koinos/broadcast/broadcast.proto
- koinos/mempool/mempool.proto
- koinos/rpc/mempool/mempool_rpc.proto
Resolves #265
Allows tracking of system resources on pending transactions and clean up messages in mempool.
> Pending transaction system resources

- koinos/rpc/mempool/mempool_rpc.proto
Resolves #267
Adds a mempool rpc to query pending transactions by id.
> get_pending_transactions_by_id
